//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyInfo
    {
        public int Id { get; set; }
        public string ProjectId { get; set; }
        public string UserApply { get; set; }
        public System.DateTime Time { get; set; }
        public string UserConfirm { get; set; }
        public string TimeConfirm { get; set; }
        public int Batch { get; set; }
        public bool ConfirmFlag { get; set; }
    }
}
