//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyCargoInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplyCargoInfo()
        {
            this.IncomingFlag = 0;
            this.ShippingFlag = 0;
        }
    
        public int Id { get; set; }
        public int ChangeCount { get; set; }
        public string ProjectId { get; set; }
        public int Batch { get; set; }
        public int IncomingFlag { get; set; }
        public int ShippingFlag { get; set; }
        public string UserIncoming { get; set; }
        public System.DateTime TimeIncoming { get; set; }
        public string UserShipping { get; set; }
        public string TimeShipping { get; set; }
        public string CargoName { get; set; }
    }
}
