//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargoInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CargoInfo()
        {
            this.DelFlag = false;
            this.CanDel = false;
            this.GoodsInfo = new HashSet<GoodsInfo>();
        }
    
        public int Id { get; set; }
        public string CargoName { get; set; }
        public string Unit { get; set; }
        public decimal CargoCount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool DelFlag { get; set; }
        public string Specifications { get; set; }
        public string Type { get; set; }
        public string LastCargoName { get; set; }
        public string Area { get; set; }
        public bool CanDel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsInfo> GoodsInfo { get; set; }
    }
}
