//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargoLogInfo
    {
        public int Id { get; set; }
        public Nullable<bool> IsIncome { get; set; }
        public decimal ChangeCount { get; set; }
        public int CargoInfoId { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public int UserId { get; set; }
        public string Desc { get; set; }
        public string TakenName { get; set; }
    }
}
