//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplyInfo()
        {
            this.DelFlag = false;
            this.CanDel = false;
        }
    
        public int Id { get; set; }
        public string Company { get; set; }
        public string SupplyName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public bool DelFlag { get; set; }
        public bool CanDel { get; set; }
        public Nullable<int> CategoryId { get; set; }
    }
}
